baseURL: 'https://vatshvan.github.io/'
title: 'Vatsh Van | Quantitative Research & Autonomous Systems'
theme: ['github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5']
ignoreFiles: ["featured\\.svg$"]


menu:
  main:
    - name: Home
      url: '/home/'
      weight: 10
    - name: Experience
      url: '/experience/'
      weight: 20
    - name: Projects
      url: '/project/'
      weight: 30
    - name: Publications
      url: '/publication/'
      weight: 40
    - name: Resume
      url: '/resume/'
      weight: 50

minify:
  disableXML: true
  minifyOutput: true