baseURL: 'https://vatshvan.github.io/'
title: 'Vatsh Van'

module:
  imports:
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5

minifyOutput: true
minify:
  disableXML: true
menus: []