baseURL: 'https://vatshvan.github.io/'
title: 'Vatsh Van | Quantitative Research & Autonomous Systems'
theme: ['github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5']

menu:
  main:
    - name: Home
      url: '#about'
      weight: 10
    - name: Experience
      url: '#experience'
      weight: 20
    - name: Projects
      url: '#projects'
      weight: 30
    - name: Publications
      url: '#publications'
      weight: 40
    - name: Resume
      url: 'uploads/Vatsh_Van_Resume.pdf'
      weight: 50

minify:
  disableXML: true
  minifyOutput: true